version: "4.36.0"
services:
  contenedorfront:
    build : .
    ports:
      - "3001:3001"
    links:
      -  postgresqldb
  postgresqldb:
    image: postgresql
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin