// // app/layout.tsx
// "use client"; // Añadir esta línea para que Next.js trate este componente como un Client Component

// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";
// import { useState } from "react";
// import Sidebar from "@/components/Sidebar"; // Ajusta la ruta si está en otra ubicación
// import Header from "@/components/Header";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   const [isSidebarExpanded, setIsSidebarExpanded] = useState(false);

//   const toggleSidebar = () => {
//     setIsSidebarExpanded(!isSidebarExpanded);
//   };

//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
        
//         <div className="min-h-screen bg-gray-100 flex">
//           {/* Sidebar */}
//           <Sidebar isExpanded={isSidebarExpanded} toggleSidebar={toggleSidebar} />
//           {/* <Header/> */}

          
//           {/* Main Content */}
//           <div >
//             {children}
//           </div>
//         </div>
//       </body>
//     </html>
//   );
// }




import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/theme-provider"


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="flex min-h-screen w-full flex-col bg-muted/40">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <Header/>

        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
